---
name: Time-Piece-Adaptive
version: !!perl/hash:Module::Build::Version
  original: 0.02
  version:
    - 0
    - 20
author:
  - 'Derek Price <derek@ximbiot.com>'
abstract: |-
  subclass of Time::Piece which allows the default
  stringification function to be set.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Time::Piece: 0
build_requires:
  Test::More: 0
provides:
  Time::Piece::Adaptive:
    file: lib/Time/Piece/Adaptive.pm
    version: 0.02
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
